export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {/* <script>
        if (localStorage.theme === 'dark' || (!('theme' in localStorage) &&
        window.matchMedia('(prefers-color-scheme: dark)').matches)){" "}
        {document.documentElement.classList.add("dark")} else{" "}
        {document.documentElement.classList.remove("dark")}
      </script> */}
      {/* <script>
        {`if (localStorage.theme === 'dark' || (!('theme' in localStorage) &&
        window.matchMedia('(prefers-color-scheme: dark)').matches)){" "}
        {document.documentElement.classList.add("dark")} else{" "}
        {document.documentElement.classList.remove("dark")}`}
      </script> */}
    </>
  );
}
