import Script from 'next/script'

export default function Head() {
  return (
    <>
      <title>Kent C. Dodds</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <Script src="https://cdn.botpress.cloud/webchat/v0/inject.js" strategy="afterInteractive"/>
      <Script src="https://mediafiles.botpress.cloud/10b57620-20b1-4ec9-aa5f-a4d5c2e252a9/webchat/config.js" strategy="lazyOnload" />
    </>
  );
}
